name: Sync Staging to Production

on:
  workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SANITY_PROJECT: ${{ secrets.SANITY_PROJECT }}
      SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli

      - name: Sync Staging to Production
        run: node sync-to-staging.js
